name: matrix-test
on: push
jobs:
    test-matrix:
        continue-on-error: true
        strategy:
            matrix:
                 node-version: [12,14,16]
                 operating-system: [ubuntu-latest,window-latest]
        runs-on: ${{matrix.operating-system}}
        steps:
          - name: Get code
            uses: actions/checkout@v4
          - name: Install Node
            uses: actions/setup-node@v4
            with:
                node-version: ${{matrix.node-version}}
          - name: install depencies
            run: npm ci
          - name: Build the project
            run: npm run build



           
