name: main to be used as workflow deploy
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: The name of the deployable artifact files
                required:  false
                default: dist
                type: string
        outputs:
            result:
                description: the result of deployment operation
                value: ${{ jobs.deploy.outputs.outcome}}
jobs:
    deploy:
        outputs:
             outcome: ${{ steps.publish.outputs.step-result}}
        runs-on: ubuntu-latest
        steps:
            - name: Get build artifacts
              uses: actions/download-artifact@v3
              with:
                name: ${{inputs.artifact-name}}
            - name: List my files
              run: ls
            - name: Deploy
              run: echo "Deploying..."
            - name: set Result output
              id: publish
              run: echo "step-result=success" >> $GITHUB_OUTPUT